# Generated by Django 4.2.3 on 2023-08-02 20:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('folio', models.CharField(editable=False, max_length=25, null=True, unique=True)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('titulo_us', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo en ingles')),
                ('contenido', models.CharField(blank=True, max_length=400, null=True, verbose_name='Contenido del banner')),
                ('contenido_us', models.CharField(blank=True, max_length=400, null=True, verbose_name='Contenido en ingles del banner')),
                ('multimedia', models.FileField(upload_to='banner/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
