# Generated by Django 4.2.4 on 2023-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentarios en ingles'),
        ),
    ]
