# Generated by Django 4.2.4 on 2023-08-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_banner_comentario_us_alter_banner_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='banner/', verbose_name='Video banner'),
        ),
    ]
