# Generated by Django 4.2.4 on 2023-08-04 20:59

import apps.base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_landing_page_delete_infraestructura'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='landing-page', validators=[apps.base.validators.validate_pdf_file], verbose_name='Selecionar pdf para descargar'),
        ),
        migrations.AlterField(
            model_name='landing_page',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='landing-page/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='landing_page',
            name='tema',
            field=models.CharField(blank=True, choices=[('infraestructura', 'Infraestructura y logistica'), ('inversion', 'Oportunidad de Inversión'), ('incentivos', 'Incentivos')], max_length=40, null=True, verbose_name='Elige el a cargar a informacion'),
        ),
    ]
