# Generated by Django 4.2.4 on 2023-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_landing_page_pdf_alter_landing_page_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing_page',
            name='tema',
            field=models.CharField(blank=True, choices=[('infraestructura', 'Infraestructura y logistica'), ('inversion', 'Oportunidad de Inversión'), ('incentivos', 'Incentivos'), ('real-state', 'Real State'), ('dossier', 'Dossier de inversión')], max_length=40, null=True, verbose_name='Elige el a cargar a informacion'),
        ),
    ]
