# Generated by Django 4.2.4 on 2023-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_landing_page_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='landing_page',
            name='tema',
            field=models.CharField(blank=True, choices=[('infraestructura', 'Infraestructura y logistica'), ('inversion', 'Oportunidad de Inversión'), ('incentivos', 'Incentivos'), ('real-state', 'Real State'), ('dossier', 'Dossier de inversión')], max_length=40, null=True, verbose_name='Elige tema a cargar a informacion'),
        ),
    ]
